import { supabase } from '@/lib/supabase';
import { CVData } from './cvService';

export const aiService = {
  /**
   * Traduz o conteúdo do CV inteiro para inglês usando IA.
   */
  translateCV: async (cvData: Partial<CVData>): Promise<Partial<CVData>> => {
    try {
      const { data, error } = await supabase.functions.invoke('generate-ai-content', {
        body: {
          action: 'translate_cv',
          payload: cvData
        }
      });

      if (error) {
        throw error;
      }

      if (!data?.data) {
        throw new Error('No translated data returned from AI');
      }

      return data.data;
    } catch (err: any) {
      console.error('Error translating CV with AI:', err);
      throw new Error(err.message || 'Falha ao traduzir CV');
    }
  },

  /**
   * Gera uma carta de apresentação usando IA baseada no perfil e nas preferências.
   */
  generateLetter: async (letterData: {
    nomeCompleto: string;
    cargoDesejado: string;
    nomeEmpresa: string;
    experienciaPrincipal: string;
    habilidadesPrincipais: string;
    motivacaoVaga: string;
    tone: 'formal' | 'modern' | 'simple';
    experience: 'junior' | 'mid' | 'senior';
  }): Promise<string> => {
    try {
      const { data, error } = await supabase.functions.invoke('generate-ai-content', {
        body: {
          action: 'generate_letter',
          payload: letterData
        }
      });

      if (error) {
        throw error;
      }

      if (!data?.data) {
        throw new Error('No letter generated by AI');
      }

      return data.data;
    } catch (err: any) {
      console.error('Error generating letter with AI:', err);
      throw new Error(err.message || 'Falha ao gerar carta');
    }
  }
};
