// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eriqmurxoqhlbblaubnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyaXFtdXJ4b3FobGJibGF1Ym5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3ODg4NzAsImV4cCI6MjA2MjM2NDg3MH0.PYUSERM3e3At0wdVFdrxEwDKaUCEsvUjGQ8zb3I7h2Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);